### PR TITLE
making fusion files optional for mip-rna

### PR DESCRIPTION
**Pull request by jemten**
## Description
THIS PR makes the fusion files generated by MIP-rna an optional output.  

### How to prepare for test
- [x] ssh to hasta.scilifelab.se
- [x] Use stage: `us`
- [x] Paxa the environment: `paxa`
- [x] Install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_hermes -t hermes -b no-mip-fusion`

### How to test
- [x] Remove fusion files from `finequagga_deliverables.yaml`
- [x] Do `cg workflow mip-rna store finequagga`
- [x] Do `housekeeper get bundle -v finequagga`

### Expected test outcome
- [x] Check that the files are stored in housekeeper.
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] Tests executed by AJ
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Comment by jemten** [comment]
No fusion reports are stored

```
θ62° [anders.jemt@hasta:/home/proj/stage/rare-disease/cases/finequagga/analysis]└2 [S_base] 6s $ cg workflow mip-rna store finequagga
/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Demux.samples to refer to viewonly relationship Sample.demuxes should include sync_backref=False set on the Demux.samples relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Sample.demuxes to refer to viewonly relationship Demux.samples should include sync_backref=False set on the Sample.demuxes relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
Case finequagga exists in Status DB
Storing bundle data in Housekeeper for finequagga
Converting pipeline deliverables to CG deliverables
Running command /home/proj/stage/bin/miniconda3/envs/S_hermes/bin/hermes convert deliverables --pipeline mip-rna /home/proj/stage/rare-disease/cases/finequagga/analysis/finequagga_deliverables.yaml
Fetching bundle with name: finequagga
Created new version
Fetching tag with name: coverage
Fetching tag with name: vogue
Fetching tag with name: sample-info
Fetching tag with name: mip-analyse
Fetching tag with name: junction
Fetching tag with name: stringtie
Fetching tag with name: vcf-snv-research
Fetching tag with name: gffcompare
Fetching tag with name: exe-ver
Fetching tag with name: storage
Fetching tag with name: salmon-quant
Fetching tag with name: cram
Fetching tag with name: finequagga
Fetching tag with name: pedigree-yaml
Fetching tag with name: multiqc-json
Fetching tag with name: pedigree
Fetching tag with name: audit
Fetching tag with name: mip-config
Fetching tag with name: reference-info
Fetching tag with name: ACC5963A1
Fetching tag with name: bed
Fetching tag with name: scout
Fetching tag with name: vcf-snv-clinical
Fetching tag with name: bigwig
Fetching tag with name: deliverable
Fetching tag with name: mip-log
Fetching tag with name: qc-metrics
Fetching tag with name: assembly
Fetching tag with name: asereadcounter
Fetching tag with name: multiqc-html
Fetching tag with name: config
Use global root path /home/proj/stage/housekeeper-bundles
created new bundle version dir: /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/ACC5963A1/salmon_quant/ACC5963A1_lanes_1234_quant.sf -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_quant.sf
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/ACC5963A1/build_sj_tracks/ACC5963A1_lanes_1234_star_sorted_sj.bigWig -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_star_sorted_sj.bigWig
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/ACC5963A1/build_sj_tracks/ACC5963A1_lanes_1234_star_sorted_sj.bed.gz -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_star_sorted_sj.bed.gz
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/ACC5963A1/build_sj_tracks/ACC5963A1_lanes_1234_star_sorted_sj.bed.gz.tbi -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_star_sorted_sj.bed.gz.tbi
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/ACC5963A1/stringtie_ar/ACC5963A1_lanes_1234_trim_star_sorted_merged_strg.gtf -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_trim_star_sorted_merged_strg.gtf
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/ACC5963A1/gffcompare_ar/ACC5963A1_lanes_1234_trim_star_sorted_merged_strg_gffcmp.gtf -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_trim_star_sorted_merged_strg_gffcmp.gtf
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/ACC5963A1/markduplicates/ACC5963A1_lanes_1234_trim_star_sorted_merged_md.cram -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_trim_star_sorted_merged_md.cram
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/ACC5963A1/markduplicates/ACC5963A1_lanes_1234_trim_star_sorted_merged_md.cram.crai -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_trim_star_sorted_merged_md.cram.crai
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/ACC5963A1/gatk_asereadcounter/ACC5963A1_lanes_1234_trim_star_sorted_merged_md_splitncigar_brecal_haptc_filtered_ase.csv -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_trim_star_sorted_merged_md_splitncigar_brecal_haptc_filtered_ase.csv
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/finequagga/vcfparser_ar/finequagga_comb_norm_vep_parsed.all.vcf.gz -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_comb_norm_vep_parsed.all.vcf.gz
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/finequagga/vcfparser_ar/finequagga_comb_norm_vep_parsed.all.vcf.gz.tbi -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_comb_norm_vep_parsed.all.vcf.gz.tbi
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/finequagga/vcfparser_ar/finequagga_comb_norm_vep_parsed.selected.vcf.gz -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_comb_norm_vep_parsed.selected.vcf.gz
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/finequagga/vcfparser_ar/finequagga_comb_norm_vep_parsed.selected.vcf.gz.tbi -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_comb_norm_vep_parsed.selected.vcf.gz.tbi
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/finequagga_metrics_deliverables.yaml -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_metrics_deliverables.yaml
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/finequagga/qccollect_ar/finequagga_qc_metrics.yaml -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_qc_metrics.yaml
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/finequagga/version_collect_ar/finequagga_vcol.yaml -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_vcol.yaml
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/finequagga/multiqc_ar/multiqc_report.html -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/multiqc_report.html
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/finequagga/multiqc_ar/multiqc_data/multiqc_data.json -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/multiqc_data.json
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/mip_log/2023-05-22/mip_2023-05-22T17:30:25.log -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/mip_2023-05-22T17:30:25.log
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/finequagga_qc_sample_info.yaml -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_qc_sample_info.yaml
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/finequagga_config.yaml -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_config.yaml
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/mip12.0-rna-stage.yaml -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/mip12.0-rna-stage.yaml
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/finequagga/finequagga.fam -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga.fam
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/pedigree.yaml -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/pedigree.yaml
linked file: /home/proj/stage/rare-disease/mip/validation/20230516/finequagga/analysis/reference_info.yaml -> /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/reference_info.yaml
Analysis successfully stored in Housekeeper: finequagga : 2023-06-29 17:41:41
Storing analysis in StatusDB for finequagga
Analysis successfully stored in StatusDB: finequagga : 2023-06-29 17:41:41
Action None set for case finequagga
[anders.jemt@hasta:/home/proj/stage/rare-disease/cases/finequagga/analysis]└2 [S_base] 26s $
θ62° [anders.jemt@hasta:/home/proj/stage/rare-disease/cases/finequagga/analysis]└2 [S_base] $
θ60° [anders.jemt@hasta:/home/proj/stage/rare-disease/cases/finequagga/analysis]└2 [S_base] $ housekeeper get bundle -v finequagga
2023-06-29 17:45:46 hasta.scilifelab.se housekeeper.cli.core[83848] INFO Use root path /home/proj/stage/housekeeper-bundles
2023-06-29 17:45:47 hasta.scilifelab.se housekeeper.store.api.handlers.read[83848] INFO Fetching all bundles
2023-06-29 17:45:47 hasta.scilifelab.se housekeeper.store.api.handlers.read[83848] INFO Fetching bundle with name: finequagga
                        📦 Bundle table 📦
┏━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ ID    ┃ Bundle name ┃ Version IDs                 ┃ Created    ┃
┡━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ 40603 │ finequagga  │ 143973, 96185, 95529, 42563 │ 2021-06-03 │
└───────┴─────────────┴─────────────────────────────┴────────────┘
2023-06-29 17:45:47 hasta.scilifelab.se housekeeper.store.api.handlers.read[83848] INFO Fetching version with id: 143973
2023-06-29 17:45:47 hasta.scilifelab.se housekeeper.store.api.handlers.read[83848] INFO Fetching bundle with id: 40603
                               📕 Version table 📕
┏━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━┓
┃ ID     ┃ Bundle name ┃ Nr files ┃ Included   ┃ Archived ┃ Created    ┃ Expires ┃
┡━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━┩
│ 143973 │ finequagga  │ 25       │ 2023-06-29 │          │ 2023-06-29 │         │
└────────┴─────────────┴──────────┴────────────┴──────────┴────────────┴─────────┘
2023-06-29 17:45:47 hasta.scilifelab.se housekeeper.store.api.handlers.read[83848] INFO Fetching files from version 143973
                                                                                             📜 Files table 📜
┏━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ID      ┃ File name                                                                                                                                            ┃ Tags                                    ┃
┡━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 4088646 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_quant.sf                                                             │ ACC5963A1, storage, salmon-quant        │
│ 4088647 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_star_sorted_sj.bigWig                                                │ coverage, bigwig, ACC5963A1, scout      │
│ 4088648 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_star_sorted_sj.bed.gz                                                │ bed, ACC5963A1, scout, junction         │
│ 4088649 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_star_sorted_sj.bed.gz.tbi                                            │ bed, ACC5963A1, scout, junction         │
│ 4088650 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_trim_star_sorted_merged_strg.gtf                                     │ ACC5963A1, storage, assembly, stringtie │
│ 4088651 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_trim_star_sorted_merged_strg_gffcmp.gtf                              │ ACC5963A1, storage, gffcompare          │
│ 4088652 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_trim_star_sorted_merged_md.cram                                      │ cram, ACC5963A1, scout                  │
│ 4088653 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_trim_star_sorted_merged_md.cram.crai                                 │ cram, ACC5963A1, scout                  │
│ 4088654 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/ACC5963A1_lanes_1234_trim_star_sorted_merged_md_splitncigar_brecal_haptc_filtered_ase.csv │ ACC5963A1, storage, asereadcounter      │
│ 4088655 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_comb_norm_vep_parsed.all.vcf.gz                                                │ vcf-snv-research, storage, finequagga   │
│ 4088656 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_comb_norm_vep_parsed.all.vcf.gz.tbi                                            │ vcf-snv-research, storage, finequagga   │
│ 4088657 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_comb_norm_vep_parsed.selected.vcf.gz                                           │ vcf-snv-clinical, storage, finequagga   │
│ 4088658 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_comb_norm_vep_parsed.selected.vcf.gz.tbi                                       │ vcf-snv-clinical, storage, finequagga   │
│ 4088659 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_metrics_deliverables.yaml                                                      │ qc-metrics, finequagga, deliverable     │
│ 4088660 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_qc_metrics.yaml                                                                │ qc-metrics, finequagga, audit           │
│ 4088661 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_vcol.yaml                                                                      │ exe-ver, finequagga                     │
│ 4088662 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/multiqc_report.html                                                                       │ multiqc-html, finequagga                │
│ 4088663 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/multiqc_data.json                                                                         │ multiqc-json, vogue, finequagga         │
│ 4088664 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/mip_2023-05-22T17:30:25.log                                                               │ mip-log, finequagga                     │
│ 4088665 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_qc_sample_info.yaml                                                            │ sample-info, finequagga                 │
│ 4088666 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga_config.yaml                                                                    │ mip-config, finequagga                  │
│ 4088667 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/mip12.0-rna-stage.yaml                                                                    │ config, mip-analyse, finequagga         │
│ 4088668 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/finequagga.fam                                                                            │ pedigree, storage, finequagga           │
│ 4088669 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/pedigree.yaml                                                                             │ pedigree-yaml, finequagga               │
│ 4088670 │ /home/proj/stage/housekeeper-bundles/finequagga/2023-06-29/reference_info.yaml                                                                       │ mip-analyse, reference-info, finequagga │
└─────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────┘
θ60° [anders.jemt@hasta:/home/proj/stage/rare-disease/cases/finequagga/analysis]└2 [S_base] 5s $
```

**Review by henrikstranneheim — APPROVED** [review]
👍

**Review by SofiaOtero — APPROVED** [review]
🙌

**Comment by jemten** [comment]
deployed 
```
θ62° 17d [hiseq.clinical@hasta:~] [P_base] $ bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-prod.sh -e P_hermes -t hermes -b main
Collecting git+https://github.com/Clinical-Genomics/hermes@main
  Running command git clone --quiet https://github.com/Clinical-Genomics/hermes /home/hiseq.clinical/tmp/pip-req-build-8dip0xbg
  Cloning https://github.com/Clinical-Genomics/hermes (to revision main) to ./tmp/pip-req-build-8dip0xbg
  Resolved https://github.com/Clinical-Genomics/hermes to commit d193ed8808219b6fdfa3514e3fd22a5623ca82e0
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: cg-hermes
  Building wheel for cg-hermes (pyproject.toml): started
  Building wheel for cg-hermes (pyproject.toml): finished with status 'done'
  Created wheel for cg-hermes: filename=cg_hermes-1.12.1-py3-none-any.whl size=24590 sha256=1ee18274a23cd30f8a91e633fe420726d4359ee6e79de4efce7c3268411cc38a
  Stored in directory: /home/hiseq.clinical/tmp/pip-ephem-wheel-cache-6krb93ek/wheels/23/c7/d3/f04e12c1ae82ea0a7172f84d1ed4b8a95fd291854e1f9ea1a8
Successfully built cg-hermes
Installing collected packages: cg-hermes
  Attempting uninstall: cg-hermes
    Found existing installation: cg-hermes 1.12.0
    Uninstalling cg-hermes-1.12.0:
      Successfully uninstalled cg-hermes-1.12.0
Successfully installed cg-hermes-1.12.1
Collecting git+https://github.com/Clinical-Genomics/hermes@main
  Running command git clone --quiet https://github.com/Clinical-Genomics/hermes /home/hiseq.clinical/tmp/pip-req-build-l2w8hprr
  Cloning https://github.com/Clinical-Genomics/hermes (to revision main) to ./tmp/pip-req-build-l2w8hprr
  Resolved https://github.com/Clinical-Genomics/hermes to commit d193ed8808219b6fdfa3514e3fd22a5623ca82e0
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: bump2version<2.0.0,>=1.0.1 in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cg-hermes==1.12.1) (1.0.1)
Requirement already satisfied: cgmodels<0.11.0,>=0.10.3 in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cg-hermes==1.12.1) (0.10.7)
Requirement already satisfied: coloredlogs<15.0,>=14.0 in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cg-hermes==1.12.1) (14.3)
Requirement already satisfied: pydantic<2.0.0,>=1.7.3 in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cg-hermes==1.12.1) (1.10.9)
Requirement already satisfied: pyyaml<6.0.0,>=5.3.1 in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cg-hermes==1.12.1) (5.4.1)
Requirement already satisfied: tabulate<0.9.0,>=0.8.7 in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cg-hermes==1.12.1) (0.8.10)
Requirement already satisfied: typer<0.10.0,>=0.9.0 in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cg-hermes==1.12.1) (0.9.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.5.0 in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cg-hermes==1.12.1) (4.6.3)
Requirement already satisfied: dataclasses in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cgmodels<0.11.0,>=0.10.3->cg-hermes==1.12.1) (0.6)
Requirement already satisfied: atomicwrites in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cgmodels<0.11.0,>=0.10.3->cg-hermes==1.12.1) (1.4.1)
Requirement already satisfied: attrs in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cgmodels<0.11.0,>=0.10.3->cg-hermes==1.12.1) (23.1.0)
Requirement already satisfied: colorama in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cgmodels<0.11.0,>=0.10.3->cg-hermes==1.12.1) (0.4.6)
Requirement already satisfied: coverage in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cgmodels<0.11.0,>=0.10.3->cg-hermes==1.12.1) (7.2.7)
Requirement already satisfied: importlib-metadata in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cgmodels<0.11.0,>=0.10.3->cg-hermes==1.12.1) (6.6.0)
Requirement already satisfied: more-itertools in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cgmodels<0.11.0,>=0.10.3->cg-hermes==1.12.1) (9.1.0)
Requirement already satisfied: packaging in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cgmodels<0.11.0,>=0.10.3->cg-hermes==1.12.1) (23.1)
Requirement already satisfied: pluggy in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cgmodels<0.11.0,>=0.10.3->cg-hermes==1.12.1) (1.0.0)
Requirement already satisfied: py in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cgmodels<0.11.0,>=0.10.3->cg-hermes==1.12.1) (1.11.0)
Requirement already satisfied: pyparsing in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cgmodels<0.11.0,>=0.10.3->cg-hermes==1.12.1) (3.0.9)
Requirement already satisfied: pytest in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cgmodels<0.11.0,>=0.10.3->cg-hermes==1.12.1) (7.3.1)
Requirement already satisfied: pytest-cov in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cgmodels<0.11.0,>=0.10.3->cg-hermes==1.12.1) (4.1.0)
Requirement already satisfied: wcwidth in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cgmodels<0.11.0,>=0.10.3->cg-hermes==1.12.1) (0.2.6)
Requirement already satisfied: zipp in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from cgmodels<0.11.0,>=0.10.3->cg-hermes==1.12.1) (3.15.0)
Requirement already satisfied: humanfriendly>=7.1 in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from coloredlogs<15.0,>=14.0->cg-hermes==1.12.1) (10.0)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from typer<0.10.0,>=0.9.0->cg-hermes==1.12.1) (8.1.3)
Requirement already satisfied: iniconfig in /home/proj/production/bin/miniconda3/envs/P_hermes/lib/python3.11/site-packages (from pytest->cgmodels<0.11.0,>=0.10.3->cg-hermes==1.12.1) (2.0.0)
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/hiseq.clinical
done.
Log deploy... done.
hermes version: 1.12.1
```

**Pull request merged**
