### PR TITLE
Update jinja2

### PR DESCRIPTION
**Pull request by henrikstranneheim**
## Description
*This PR adds/fixes ...*

### How to prepare for test
- [ ] ssh to hasta.scilifelab.se
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_hermes -t hermes -b update-jinja2`

### How to test
- [ ] Do ...

### Expected test outcome
- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
👍 
```
tranneheim@hasta:~] [S_base] $ hermes validate tags balsamic
2024-08-26 08:32:00 hasta.scilifelab.se cg_hermes.cli.validate[73914] INFO Validating balsamic common tags
2024-08-26 08:32:00 hasta.scilifelab.se cg_hermes.cli.validate[73914] INFO Tag map looks fine

**Review by islean — APPROVED** [review]
LGTM!

**Review by mathiasbio — APPROVED** [review]
Looks good! Though I'm still no expert on hermes or jinja! 😬 🙏

**Comment by henrikstranneheim** [comment]
Deployed to prod
´´´
Log deploy... done.
hermes version: 4.4.11

**Pull request merged**
