### PR TITLE
Python update

### PR DESCRIPTION
**Pull request by raysloks**
## Description
Updates Hermes to use python 3.11
Additionally, updates the versions of typing-extensions, typer, and pytest
Closes https://github.com/Clinical-Genomics/hermes/issues/78

### How to prepare for test
- [x] ssh to hasta.scilifelab.se
- [x] Use stage: `us`
- [x] Paxa the environment: `paxa`
- [x] Install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_hermes -t hermes -b [THIS-BRANCH-NAME]`

### How to test
- [x] Run `hermes`
- [x] Run a `cg workflow` store command
- [x] Run CI

### Expected test outcome
- [x] Check that the tests don't give any errors
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [x] Tests executed by EBE
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Deploy this branch

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
Nice! Could your run a store cmd for a workflow on Hasta stage in a python updated S_hermes conda env? If unsure how could you reach out to @ivadym ?

**Comment by raysloks** [comment]
I've tried running `cg workflow mip-dna store justhusky` (is that the right command?), but I'm getting some errors:
```
θ63° [emil.bertilsson@hasta:~]└5 [S_hermes] $ cg workflow mip-dna store justhusky
/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Demux.samples to refer to viewonly relationship Sample.demuxes should include sync_backref=False set on the Demux.samples relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Sample.demuxes to refer to viewonly relationship Demux.samples should include sync_backref=False set on the Sample.demuxes relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
Case justhusky exists in Status DB
Storing bundle data in Housekeeper for justhusky
Converting pipeline deliverables to CG deliverables
Running command /home/proj/stage/bin/miniconda3/envs/S_hermes/bin/hermes convert deliverables --pipeline mip-dna /home/proj/stage/rare-disease/cases/justhusky/analysis/justhusky_deliverables.yaml
Optional file /home/proj/stage/rare-disease/cases/justhusky/analysis/justhusky/me_merge_vcfs/justhusky_me.vcf.gz not found, removing from bundle
Optional file /home/proj/stage/rare-disease/cases/justhusky/analysis/justhusky/me_merge_vcfs/justhusky_me.vcf.gz.tbi not found, removing from bundle
Optional file /home/proj/stage/rare-disease/cases/justhusky/analysis/justhusky/me_filter/justhusky_me_ann_vep_filter.vcf.gz not found, removing from bundle
Optional file /home/proj/stage/rare-disease/cases/justhusky/analysis/justhusky/me_filter/justhusky_me_ann_vep_filter.vcf.gz.tbi not found, removing from bundle
Optional file /home/proj/stage/rare-disease/cases/justhusky/analysis/justhusky/me_filter/justhusky_me_ann_vep_filter.selected.vcf.gz not found, removing from bundle
Optional file /home/proj/stage/rare-disease/cases/justhusky/analysis/justhusky/me_filter/justhusky_me_ann_vep_filter.selected.vcf.gz.tbi not found, removing from bundle
Error storing deliverables for case justhusky - 4 validation errors for CGDeliverables
files -> 1
  Mandatory file cannot be found at /home/proj/stage/rare-disease/cases/justhusky/analysis/justhusky/endvariantannotationblock/justhusky_gatkcomb_rhocall_norm_af_mt_frqf_cadd_vep_parsed.vcf.gz (type=assertion_error)
files -> 2
  Mandatory file cannot be found at /home/proj/stage/rare-disease/cases/justhusky/analysis/justhusky/endvariantannotationblock/justhusky_gatkcomb_rhocall_norm_af_mt_frqf_cadd_vep_parsed.vcf.gz.tbi (type=assertion_error)
files -> 3
  Mandatory file cannot be found at /home/proj/stage/rare-disease/cases/justhusky/analysis/justhusky/endvariantannotationblock/justhusky_gatkcomb_rhocall_norm_af_mt_frqf_cadd_vep_parsed.selected.vcf.gz (type=assertion_error)
files -> 4
  Mandatory file cannot be found at /home/proj/stage/rare-disease/cases/justhusky/analysis/justhusky/endvariantannotationblock/justhusky_gatkcomb_rhocall_norm_af_mt_frqf_cadd_vep_parsed.selected.vcf.gz.tbi (type=assertion_error)
Traceback (most recent call last):
  File "/home/proj/stage/bin/miniconda3/envs/S_main/bin/cg", line 8, in <module>
    sys.exit(base())
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/cg/cli/workflow/commands.py", line 115, in store
    analysis_api.upload_bundle_housekeeper(case_id=case_id)
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/cg/meta/workflow/analysis.py", line 140, in upload_bundle_housekeeper
    bundle_data: dict = self.get_hermes_transformed_deliverables(case_id)
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/cg/meta/workflow/analysis.py", line 213, in get_hermes_transformed_deliverables
    created=self.get_bundle_created_date(case_id),
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/cg/apps/hermes/hermes_api.py", line 48, in create_housekeeper_bundle
    deliverables_file=deliverables, pipeline=pipeline, analysis_type=analysis_type
  File "/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/cg/apps/hermes/hermes_api.py", line 36, in convert_deliverables
    return CGDeliverables.parse_raw(self.process.stdout)
  File "pydantic/main.py", line 544, in pydantic.main.BaseModel.parse_raw
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 4 validation errors for CGDeliverables
files -> 1
  Mandatory file cannot be found at /home/proj/stage/rare-disease/cases/justhusky/analysis/justhusky/endvariantannotationblock/justhusky_gatkcomb_rhocall_norm_af_mt_frqf_cadd_vep_parsed.vcf.gz (type=assertion_error)
files -> 2
  Mandatory file cannot be found at /home/proj/stage/rare-disease/cases/justhusky/analysis/justhusky/endvariantannotationblock/justhusky_gatkcomb_rhocall_norm_af_mt_frqf_cadd_vep_parsed.vcf.gz.tbi (type=assertion_error)
files -> 3
  Mandatory file cannot be found at /home/proj/stage/rare-disease/cases/justhusky/analysis/justhusky/endvariantannotationblock/justhusky_gatkcomb_rhocall_norm_af_mt_frqf_cadd_vep_parsed.selected.vcf.gz (type=assertion_error)
files -> 4
  Mandatory file cannot be found at /home/proj/stage/rare-disease/cases/justhusky/analysis/justhusky/endvariantannotationblock/justhusky_gatkcomb_rhocall_norm_af_mt_frqf_cadd_vep_parsed.selected.vcf.gz.tbi (type=assertion_error)
```
Is there another case I could try using?

**Comment by henrikstranneheim** [comment]
@ivadym Do you have recent case on stage for Emil to use?

**Comment by ivadym** [comment]
Yes! I've just left you a cancer case  in stage that you can try storing: `cg workflow balsamic store acetuna`

**Comment by raysloks** [comment]
That seems to have worked!
```
[emil.bertilsson@hasta:~]└5 [S_hermes] 1 $ cg workflow balsamic store acetuna
/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:2231: SAWarning: Cascade settings "delete, merge, save-update" should not be combined with a viewonly=True relationship.   This configuration will raise an error in version 1.4.  Note that in versions prior to 1.4, these cascade settings may still produce a mutating effect even though this relationship is marked as viewonly=True.
  "viewonly=True." % (", ".join(sorted(non_viewonly)))
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Called undefined __fields__ on HousekeeperAPI, please wrap
Storing analysis for acetuna
/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Demux.samples to refer to viewonly relationship Sample.demuxes should include sync_backref=False set on the Demux.samples relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
/home/proj/stage/bin/miniconda3/envs/S_main/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py:1998: SAWarning: Setting backref / back_populates on relationship Sample.demuxes to refer to viewonly relationship Demux.samples should include sync_backref=False set on the Sample.demuxes relationship.  (this warning may be suppressed after 10 occurrences)
  (rel_b, rel_a, rel_b),
Case acetuna exists in Status DB
Running command /home/proj/stage/bin/miniconda3/envs/S_balsamic/bin/balsamic report deliver --sample-config /home/proj/stage/cancer/cases/acetuna/acetuna.json
Case acetuna exists in Status DB
Storing bundle data in Housekeeper for acetuna
Found analysis type tumor_panel
Converting pipeline deliverables to CG deliverables
Running command /home/proj/stage/bin/miniconda3/envs/S_hermes/bin/hermes convert deliverables --pipeline balsamic /home/proj/stage/cancer/cases/acetuna/analysis/delivery_report/acetuna.hk --analysis-type tumor_panel
Fetching bundle with name: acetuna
Created new version
Fetching tag with name: scatter
Fetching tag with name: vcf-snv-research
Fetching tag with name: tumor
Fetching tag with name: vardict
Fetching tag with name: vcf2cytosure
Fetching tag with name: qc-metrics
Fetching tag with name: delly
Fetching tag with name: germline
Fetching tag with name: scout
Fetching tag with name: vcf-sv-clinical
Fetching tag with name: vcf-snv-germline-tumor-index
Fetching tag with name: acetuna
Fetching tag with name: vcf-snv
Fetching tag with name: vcf-snv-clinical-index
Fetching tag with name: vcf-snv-clinical
Fetching tag with name: metrics
Fetching tag with name: vcf-sv-research-index
Fetching tag with name: balsamic-dag
Fetching tag with name: cram-index
Fetching tag with name: vcf-snv-index
Fetching tag with name: multiqc-json
Fetching tag with name: vcf-snv-germline-tumor
Fetching tag with name: visualization
Fetching tag with name: diagram
Fetching tag with name: svdb
Fetching tag with name: segments
Fetching tag with name: cram
Fetching tag with name: vcf-sv-index
Fetching tag with name: vcf-sv-germline-tumor-index
Fetching tag with name: vcf-sv
Fetching tag with name: vcf-sv-clinical-index
Fetching tag with name: genes
Fetching tag with name: balsamic-config
Fetching tag with name: vogue
Fetching tag with name: coverage
Fetching tag with name: ACC9362A4
Fetching tag with name: deliver
Fetching tag with name: cnvkit
Fetching tag with name: multiqc-html
Fetching tag with name: vcf-sv-germline-tumor
Fetching tag with name: vcf-sv-research
Fetching tag with name: balsamic-report
Fetching tag with name: vcf-snv-research-index
Use global root path /home/proj/stage/housekeeper-bundles
created new bundle version dir: /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/qc/acetuna_metrics_deliverables.yaml -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/acetuna_metrics_deliverables.yaml
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/bam/tumor.merged.cram -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/tumor.merged.cram
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/bam/tumor.merged.cram.crai -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/tumor.merged.cram.crai
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/cnv/tumor.merged.cns -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/tumor.merged.cns
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/cnv/tumor.merged-diagram.pdf -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/tumor.merged-diagram.pdf
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/cnv/acetuna.gene_metrics -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/acetuna.gene_metrics
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/cnv/tumor.merged-scatter.pdf -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/tumor.merged-scatter.pdf
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vcf/SNV.somatic.acetuna.vardict.vcf.gz -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/SNV.somatic.acetuna.vardict.vcf.gz
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vcf/SNV.somatic.acetuna.vardict.vcf.gz.tbi -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/SNV.somatic.acetuna.vardict.vcf.gz.tbi
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vep/SV.somatic.acetuna.svdb.research.filtered.pass.vcf.gz -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/SV.somatic.acetuna.svdb.research.filtered.pass.vcf.gz
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vep/SV.somatic.acetuna.svdb.research.filtered.pass.vcf.gz.tbi -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/SV.somatic.acetuna.svdb.research.filtered.pass.vcf.gz.tbi
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vcf/CNV.somatic.acetuna.dellycnv.cov.gz -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/CNV.somatic.acetuna.dellycnv.cov.gz
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vep/SNV.somatic.acetuna.vardict.research.filtered.pass.vcf.gz -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/SNV.somatic.acetuna.vardict.research.filtered.pass.vcf.gz
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vep/SNV.somatic.acetuna.vardict.research.filtered.pass.vcf.gz.tbi -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/SNV.somatic.acetuna.vardict.research.filtered.pass.vcf.gz.tbi
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vcf/CNV.somatic.acetuna.cnvkit.vcf2cytosure.cgh -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/CNV.somatic.acetuna.cnvkit.vcf2cytosure.cgh
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vep/SNV.somatic.acetuna.vardict.clinical.filtered.pass.vcf.gz -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/SNV.somatic.acetuna.vardict.clinical.filtered.pass.vcf.gz
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vep/SNV.somatic.acetuna.vardict.clinical.filtered.pass.vcf.gz.tbi -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/SNV.somatic.acetuna.vardict.clinical.filtered.pass.vcf.gz.tbi
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vcf/SV.somatic.acetuna.svdb.vcf.gz -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/SV.somatic.acetuna.svdb.vcf.gz
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vcf/SV.somatic.acetuna.svdb.vcf.gz.tbi -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/SV.somatic.acetuna.svdb.vcf.gz.tbi
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/qc/multiqc_report.html -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/multiqc_report.html
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/qc/multiqc_data/multiqc_data.json -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/multiqc_data.json
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vep/SV.somatic.acetuna.svdb.clinical.filtered.pass.vcf.gz -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/SV.somatic.acetuna.svdb.clinical.filtered.pass.vcf.gz
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vep/SV.somatic.acetuna.svdb.clinical.filtered.pass.vcf.gz.tbi -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/SV.somatic.acetuna.svdb.clinical.filtered.pass.vcf.gz.tbi
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vep/SV.germline.tumor.manta_germline.vcf.gz -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/SV.germline.tumor.manta_germline.vcf.gz
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vep/SV.germline.tumor.manta_germline.vcf.gz.tbi -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/SV.germline.tumor.manta_germline.vcf.gz.tbi
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vep/SNV.germline.tumor.dnascope.vcf.gz -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/SNV.germline.tumor.dnascope.vcf.gz
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/vep/SNV.germline.tumor.dnascope.vcf.gz.tbi -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/SNV.germline.tumor.dnascope.vcf.gz.tbi
linked file: /home/proj/stage/cancer/cases/acetuna/analysis/delivery_report/acetuna_report.html -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/acetuna_report.html
linked file: /home/proj/stage/cancer/cases/acetuna/acetuna.json -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/acetuna.json
linked file: /home/proj/stage/cancer/cases/acetuna/acetuna_BALSAMIC_12.0.0_graph.pdf -> /home/proj/stage/housekeeper-bundles/acetuna/2023-05-29/acetuna_BALSAMIC_12.0.0_graph.pdf
Analysis successfully stored in Housekeeper: acetuna : 2023-05-29 14:07:55
Storing analysis in StatusDB for acetuna
Analysis successfully stored in StatusDB: acetuna : 2023-05-29 14:07:55
Action None set for case acetuna
```
I've got some concerns about deploying to P_hermes. When updating the python version of a conda environment, the recommended way is to create a new environment. However, there were some issues with the wrong conda binary being used last time I tried creating a prod environment (P_gens).

**Comment by ivadym** [comment]
I would try to update the hermes stage environment first if you haven't already. I'm not sure what went wrong with P_gens, but you could use the absolute path of the conda binaries (stage and prod) just to make sure you get what you expect

**Pull request merged**
