### PR TITLE
Refactor to pep 0585

### PR DESCRIPTION
**Pull request by henrikstranneheim**
## Description

Refactor to pep 0585.

### Changed

- Refactor to pep 0585

### How to prepare for test
- [ ] ssh to hasta.scilifelab.se
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_hermes -t hermes -b refactor-to-PEP-0585`

### How to test
- [ ] Do ...

### Expected test outcome
- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Review by diitaz93 — APPROVED** [review]
👍

**Review by islean — APPROVED** [review]
🔥

**Comment by henrikstranneheim** [comment]
### hermes export tags --pipeline mip-dna 👍 
```
θ65° [henrik.stranneheim@hasta:~] [S_base] 4s 2 $ hermes export tags --pipeline mip-dna
2023-12-21 09:26:22 hasta.scilifelab.se cg_hermes.cli.export[230205] INFO Running export tags for pipeline mip-dna
| Mip-dna tags                        | Mandatory   | HK tags                          | Used by      |
|-------------------------------------|-------------|----------------------------------|--------------|
| chanjo_sexcheck                     | False       | chanjo, sex-check                | scout        |
| chromograph_upd, sites              | False       | chromograph, upd, sites          | scout        |
| chromograph_upd, regions            | False       | chromograph, upd, regions        | scout        |
| chromograph_cov, tcov               | False       | chromograph, tcov                | scout        |
| autozyg, chromograph_rhoviz         | False       | chromograph, autozyg             | scout        |
| fracsnp, chromograph_rhoviz         | False       | chromograph, fracsnp             | scout        |
| clinical, endvariantannotationblock | True        | vcf-snv-clinical                 | scout        |
| research, endvariantannotationblock | True        | vcf-snv-research                 | scout        |
| sv_str, expansionhunter             | False       | vcf-str                          | scout        |
| str_variants, expansionhunter       | False       | expansionhunter, vcf-str         | scout        |
| expansionhunter, str_alignment      | False       | expansionhunter, bam             | scout        |
| variant_catalog, expansionhunter    | False       | expansionhunter, variant-catalog | scout        |
| glnexus_merge                       | False       | deepvariant, snv, vcf            | storage      |
| markduplicates                      | False       | cram                             | scout        |
| gatk_combinevariantcallsets         | True        | snv-gbcf, snv-bcf                | genotype     |
| baf, gens_generatedata              | False       | gens, fracsnp, bed               | scout        |
| cov, gens_generatedata              | False       | gens, coverage, bed              | scout        |
| me_merge_vcfs                       | False       | retroseq, vcf                    | audit        |
| me_filter, clinical                 | False       | mobile-elements, clinical, vcf   | scout        |
| research, me_filter                 | False       | mobile-elements, research, vcf   | scout        |
| mip_analyse, config                 | True        | mip-analyse, config              | cg, audit    |
| mip_analyse, config_analysis        | True        | mip-config                       | cg, audit    |
| mip_analyse, log                    | True        | mip-log                          | audit        |
| mip_analyse, pedigree               | True        | pedigree-yaml                    | audit        |
| mip_analyse, pedigree_fam           | True        | pedigree                         | scout        |
| mip_analyse, references_info        | True        | mip-analyse, reference-info      | audit        |
| sample_info, mip_analyse            | True        | sample-info                      | cg, audit    |
| multiqc_ar, html                    | True        | multiqc-html                     | scout        |
| multiqc_ar, json                    | True        | multiqc-json                     | vogue        |
| mitodel                             | False       | mitodel                          | scout        |
| ped_check, peddy_ar                 | True        | peddy, ped-check                 | audit, scout |
| peddy, peddy_ar                     | True        | peddy, ped                       | audit, scout |
| sex_check, peddy_ar                 | True        | peddy, sex-check                 | audit, scout |
| qccollect_ar, deliverable           | True        | qc-metrics, deliverable          | audit        |
| qccollect_ar, audit                 | True        | qc-metrics, audit                | audit        |
| rhocall_viz                         | False       | rhocall-viz                      | scout        |
| coverage, sambamba_depth            | True        | coverage, sambamba-depth         | chanjo       |
| samtools_subsample_mt               | False       | bam-mt                           | scout        |
| smncopynumbercaller                 | False       | smn-calling                      | scout        |
| star_caller                         | False       | cyrius                           | scout        |
| sv_combinevariantcallsets           | True        | sv-bcf                           | audit        |
| sv_reformat, clinical               | False       | vcf-sv-clinical                  | scout        |
| sv_reformat, research               | False       | vcf-sv-research                  | scout        |
| telomerecat_ar                      | False       | telomere-calling                 | scout        |
| tiddit_coverage                     | False       | tiddit-coverage, bigwig          | scout        |
| upd_ar, regions                     | False       | upd, regions                     | scout        |
| upd_ar, sites                       | False       | upd, sites                       | scout        |
| version_collect_ar                  | True        | exe-ver                          | audit        |
| vcf2cytosure_ar                     | False       | vcf2cytosure                     | scout        |
```

**Comment by henrikstranneheim** [comment]
Deployed to production:

```
Log deploy... done.
hermes version: 1.14.3
```

**Pull request merged**
