### PR TITLE
feat(refactor): Optional

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### Change

- Refactor to PEP 604

### How to prepare for test
- [ ] ssh to hasta.scilifelab.se
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_hermes -t hermes -b refactor-to-pep-604`

### How to test
- [ ] Do ...

### Expected test outcome
- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Review by ivadym — APPROVED** [review]
👍

**Review by diitaz93 — APPROVED** [review]
👍

**Comment by henrikstranneheim** [comment]
Code executes without errors 👍 
```
θ61° [henrik.stranneheim@hasta:~] [S_base] 5s $ hermes validate tags balsamic
2024-01-11 17:12:49 hasta.scilifelab.se cg_hermes.cli.validate[248434] INFO Validating balsamic common tags
2024-01-11 17:12:49 hasta.scilifelab.se cg_hermes.cli.validate[248434] INFO Tag map looks fine
```

**Comment by henrikstranneheim** [comment]
Deployed in production:

```
Log deploy... done.
hermes version: 1.14.4
```

**Pull request merged**
