### PR TITLE
Poetry update

### PR DESCRIPTION
**Pull request by raysloks**
## Description
Closes https://github.com/Clinical-Genomics/hermes/issues/72

### How to prepare for test
- [x] ssh to hasta.scilifelab.se
- [x] Use stage: `us`
- [x] Paxa the environment: `paxa`
- [x] Install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_hermes -t hermes -b [THIS-BRANCH-NAME]`

### How to test
- [x] Do CI
- [x] Run `hermes` in `S_hermes`

### Expected test outcome
- [x] Check that CI passes
- [x] Check that `hermes` seems to work in `S_hermes`
- [x] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Deploy this branch per [DEPLOYMENT.md](https://github.com/Clinical-Genomics/hermes/blob/main/DEPLOYMENT.md)

### CODE REVIEW

**Comment by raysloks** [comment]
Installing branch on stage seems to have worked.
```
[emil.bertilsson@hasta:~/hermes]└5 [S_hermes] poetry-update ± hermes
Usage: hermes [OPTIONS] COMMAND [ARGS]...

  Manage users in the awesome CLI app.

Options:
  --loglevel [DEBUG|INFO|WARNING]
                                  Set the log level  [default: INFO]
  --version
  --install-completion [bash|zsh|fish|powershell|pwsh]
                                  Install completion for the specified shell.
  --show-completion [bash|zsh|fish|powershell|pwsh]
                                  Show completion for the specified shell, to
                                  copy it or customize the installation.

  --help                          Show this message and exit.

Commands:
  convert
  export
  validate
```

**Comment by raysloks** [comment]
Should this be a minor or a patch?

**Review by henrikstranneheim — APPROVED** [review]
👍

**Comment by henrikstranneheim** [comment]
II would call it a minor

**Review by ivadym — APPROVED** [review]
Well done 🚀 ⭐

**Pull request merged**
