### PR TITLE
Feature/mitodel

### PR DESCRIPTION
**Pull request by ramprasadn**
## Description

Add mitodel tag for mip_dna

## Review
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Comment by Mropat** [comment]
Done? is coverage in all successful MIP runs high enough to guarantee this output file?

**Comment by ramprasadn** [comment]
@Mropat Thanks for raising this point. For WGS samples, like Anders said, coverage should be enough to guarantee an output file. That said, we don’t run this analysis on whole exome samples and so I have changed the is_mandatory tag to False.  Upload to HK shouldn't be an issue anymore :)

**Review by Mropat — APPROVED** [review]

**Comment by henrikstranneheim** [comment]
@ramprasadn @Mropat Was this PR deployed to Hasta? 

@ramprasadn Did you do any test in stage on Hasta with a MIP case?

**Comment by ramprasadn** [comment]
@henrikstranneheim No. I ran MIP in my local environment to make sure that the deliverables file has mitodel entries, but I haven't validated it on stage.

**Comment by ramprasadn** [comment]
Screenshot 2021-09-13 at 14 30 13

Tested on stage and it works.

**Comment by henrikstranneheim** [comment]
Great! Do you want to sit together and deploy?

**Comment by ramprasadn** [comment]
Since Hassan's PR would also be part of this deployment, I have asked him if its okay for me to deploy master on production. Once I get a response from him, I will deploy it.

I looked at [this], and I guess only point no 8. is left for me to do on hasta. I could probably do it myself unless if there is anything else I should be wary of?  

[this]: https://github.com/Clinical-Genomics/hermes/blob/main/DEPLOYMENT.md

**Comment by ramprasadn** [comment]
Screenshot 2021-09-13 at 15 07 14
Deployed on hasta

**Pull request merged**
