### PR TITLE
feat(update): Python

### PR DESCRIPTION
**Pull request by henrikstranneheim**
## Description
*This PR adds/fixes ...*

### How to prepare for test
- [ ] ssh to hasta.scilifelab.se
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_hermes -t hermes -b updste-python

### How to test
- [ ] Do ...

### Expected test outcome
- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
### Remove and reinstall,  👍 
```
enrik.stranneheim@hasta:~] [S_base] $ conda remove --name S_hermes --all

Remove all packages in environment /home/proj/stage/bin/miniconda3/envs/S_hermes:


## Package Plan ##

  environment location: /home/proj/stage/bin/miniconda3/envs/S_hermes


The following packages will be REMOVED:

  _libgcc_mutex-0.1-main
  _openmp_mutex-5.1-1_gnu
  bzip2-1.0.8-h7b6447c_0
  ca-certificates-2023.01.10-h06a4308_0
  ld_impl_linux-64-2.38-h1181459_1
  libffi-3.4.4-h6a678d5_0
  libgcc-ng-11.2.0-h1234567_1
  libgomp-11.2.0-h1234567_1
  libstdcxx-ng-11.2.0-h1234567_1
  libuuid-1.41.5-h5eee18b_0
  ncurses-6.4-h6a678d5_0
  openssl-1.1.1t-h7f8727e_0
  pip-23.0.1-py311h06a4308_0
  python-3.11.3-h7a1cb2a_0
  readline-8.2-h5eee18b_0
  setuptools-66.0.0-py311h06a4308_0
  sqlite-3.41.2-h5eee18b_0
  tk-8.6.12-h1ccaba5_0
  tzdata-2023c-h04d1e81_0
  wheel-0.38.4-py311h06a4308_0
  xz-5.4.2-h5eee18b_0
  zlib-1.2.13-h5eee18b_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

09:19] [hiseq.clinical@hasta:~] [S_base]  $ conda create --name S_hermes python=3.12.5 pip
Retrieving notices: ...working... done
Channels:
 - bioconda
 - defaults
 - conda-forge
 - nodefaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/proj/stage/bin/miniconda3/envs/S_hermes

  added / updated specs:
    - pip
    - python=3.12.5


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ld_impl_linux-64-2.40      |       h12ee557_0         710 KB
    ------------------------------------------------------------
                                           Total:         710 KB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h5eee18b_6
  ca-certificates    pkgs/main/linux-64::ca-certificates-2024.7.2-h06a4308_0
  expat              pkgs/main/linux-64::expat-2.6.3-h6a678d5_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.40-h12ee557_0
  libffi             pkgs/main/linux-64::libffi-3.4.4-h6a678d5_1
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1
  libuuid            pkgs/main/linux-64::libuuid-1.41.5-h5eee18b_0
  ncurses            pkgs/main/linux-64::ncurses-6.4-h6a678d5_0
  openssl            pkgs/main/linux-64::openssl-3.0.15-h5eee18b_0
  pip                pkgs/main/linux-64::pip-24.2-py312h06a4308_0
  python             pkgs/main/linux-64::python-3.12.5-h5148396_1
  readline           pkgs/main/linux-64::readline-8.2-h5eee18b_0
  setuptools         pkgs/main/linux-64::setuptools-75.1.0-py312h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.45.3-h5eee18b_0
  tk                 pkgs/main/linux-64::tk-8.6.14-h39e8969_0
  tzdata             pkgs/main/noarch::tzdata-2024a-h04d1e81_0
  wheel              pkgs/main/linux-64::wheel-0.44.0-py312h06a4308_0
  xz                 pkgs/main/linux-64::xz-5.4.6-h5eee18b_1
  zlib               pkgs/main/linux-64::zlib-1.2.13-h5eee18b_1


Proceed ([y]/n)? y


Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate S_hermes
#
# To deactivate an active environment, use
#
#     $ conda deactivate

ogout
[henrik.stranneheim@hasta:~] [S_base] $ bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_hermes -t hermes -b updste-python
/home/henrik.stranneheim/tmp/tmpznmiks28: line 3: /home/proj/stage/bin/miniconda3/envs/S_hermes/bin/hermes: No such file or directory

ERROR conda.cli.main_run:execute(49): `conda run /home/proj/stage/bin/miniconda3/envs/S_hermes/bin/hermes --version` failed. (See above for error)
Collecting git+https://github.com/Clinical-Genomics/hermes@updste-python
  Cloning https://github.com/Clinical-Genomics/hermes (to revision updste-python) to ./tmp/pip-req-build-aadfe84w
  Running command git clone --quiet https://github.com/Clinical-Genomics/hermes /home/henrik.stranneheim/tmp/pip-req-build-aadfe84w
  Running command git checkout -b updste-python --track origin/updste-python
  Switched to a new branch 'updste-python'
  Branch updste-python set up to track remote branch updste-python from origin.
  Resolved https://github.com/Clinical-Genomics/hermes to commit 2f04a24c5f4ae83cc3abff5d15c907f254aa2e6d
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cg-hermes
  Building wheel for cg-hermes (pyproject.toml) ... done
  Created wheel for cg-hermes: filename=cg_hermes-4.4.13-py3-none-any.whl size=34602 sha256=87d2040503b02797d37c93cc04b62cb9568a8ce09e90642936474eb231633934
  Stored in directory: /home/henrik.stranneheim/tmp/pip-ephem-wheel-cache-c19w346f/wheels/76/20/a6/f2ab2a3576492249d55f753cda571678b8b98534dcd40ecfef
Successfully built cg-hermes
Installing collected packages: cg-hermes
Successfully installed cg-hermes-4.4.13
Collecting git+https://github.com/Clinical-Genomics/hermes@updste-python
  Cloning https://github.com/Clinical-Genomics/hermes (to revision updste-python) to ./tmp/pip-req-build-vt8xbpir
  Running command git clone --quiet https://github.com/Clinical-Genomics/hermes /home/henrik.stranneheim/tmp/pip-req-build-vt8xbpir
  Running command git checkout -b updste-python --track origin/updste-python
  Switched to a new branch 'updste-python'
  Branch updste-python set up to track remote branch updste-python from origin.
  Resolved https://github.com/Clinical-Genomics/hermes to commit 2f04a24c5f4ae83cc3abff5d15c907f254aa2e6d
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting bump2version (from cg-hermes==4.4.13)
  Downloading bump2version-1.0.1-py2.py3-none-any.whl.metadata (17 kB)
Collecting coloredlogs (from cg-hermes==4.4.13)
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Collecting pydantic (from cg-hermes==4.4.13)
  Downloading pydantic-2.9.2-py3-none-any.whl.metadata (149 kB)
Collecting pyyaml (from cg-hermes==4.4.13)
  Using cached PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting tabulate (from cg-hermes==4.4.13)
  Downloading tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Collecting typer (from cg-hermes==4.4.13)
  Downloading typer-0.12.5-py3-none-any.whl.metadata (15 kB)
Collecting typing-extensions (from cg-hermes==4.4.13)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting humanfriendly>=9.1 (from coloredlogs->cg-hermes==4.4.13)
  Using cached humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Collecting annotated-types>=0.6.0 (from pydantic->cg-hermes==4.4.13)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.23.4 (from pydantic->cg-hermes==4.4.13)
  Downloading pydantic_core-2.23.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting click>=8.0.0 (from typer->cg-hermes==4.4.13)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting shellingham>=1.3.0 (from typer->cg-hermes==4.4.13)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=10.11.0 (from typer->cg-hermes==4.4.13)
  Downloading rich-13.8.1-py3-none-any.whl.metadata (18 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=10.11.0->typer->cg-hermes==4.4.13)
  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=10.11.0->typer->cg-hermes==4.4.13)
  Downloading pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->cg-hermes==4.4.13)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading bump2version-1.0.1-py2.py3-none-any.whl (22 kB)
Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Downloading pydantic-2.9.2-py3-none-any.whl (434 kB)
Downloading pydantic_core-2.23.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 45.6 MB/s eta 0:00:00
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Using cached PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (767 kB)
Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Downloading typer-0.12.5-py3-none-any.whl (47 kB)
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Downloading rich-13.8.1-py3-none-any.whl (241 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Downloading pygments-2.18.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 6.3 MB/s eta 0:00:00
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: typing-extensions, tabulate, shellingham, pyyaml, pygments, mdurl, humanfriendly, click, bump2version, annotated-types, pydantic-core, markdown-it-py, coloredlogs, rich, pydantic, typer
Successfully installed annotated-types-0.7.0 bump2version-1.0.1 click-8.1.7 coloredlogs-15.0.1 humanfriendly-10.0 markdown-it-py-3.0.0 mdurl-0.1.2 pydantic-2.9.2 pydantic-core-2.23.4 pygments-2.18.0 pyyaml-6.0.2 rich-13.8.1 shellingham-1.5.4 tabulate-0.9.0 typer-0.12.5 typing-extensions-4.12.2
hermes --verfatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/henrik.stranneheim
done.
Log deploy... done.
hermes version: 4.4.13
[henrik.stranneheim@hasta:~] [S_base] $ hermes --version
hermes version: 4.4.13
[henrik.stranneheim@hasta:~] [S_base] $

**Comment by henrikstranneheim** [comment]
### Hermes export, 👍 
```
henrik.stranneheim@hasta:~] [S_base] $ hermes export tags --workflow balsamic
2024-09-27 09:36:04 hasta.scilifelab.se cg_hermes.cli.export[138799] INFO Running export tags for workflow: balsamic
| Balsamic tags                                                  | Mandatory   | HK tags                                   | Used by               |
|----------------------------------------------------------------|-------------|-------------------------------------------|-----------------------|
| balsamic-config                                                | True        | balsamic-config                           | audit, cg             |
| balsamic-report                                                | True        | balsamic-report                           | audit                 |
| balsamic-dag                                                   | True        | balsamic-dag                              | audit                 |
| multiqc-html, html                                             | True        | multiqc-html                              | audit, deliver, scout |
| json, multiqc-json                                             | True        | multiqc-json                              | audit                 |
| picard, alignmentsummarymetrics, multiqc                       | True        | qc-metrics, multiqc, picard-alignment     | storage, janus        |
| picard, multiqc, dups                                          | True        | qc-metrics, multiqc, picard-duplicates    | storage, janus        |
| picard, hsmetrics, multiqc                                     | True        | qc-metrics, multiqc, picard-hs            | storage, janus        |
| picard, multiqc, insertsize                                    | True        | qc-metrics, multiqc, picard-insert-size   | storage, janus        |
| picard, multiqc, wgsmetrics                                    | False       | qc-metrics, multiqc, picard-wgs           | storage, janus        |
| fastp, multiqc                                                 | True        | qc-metrics, multiqc, fastp                | storage, janus        |
| multiqc, stats, samtools                                       | True        | qc-metrics, multiqc, samtools-stats       | storage, janus        |
| somalier, multiqc                                              | False       | qc-metrics, multiqc, somalier             | storage, janus        |
| yaml, qc-metrics-yaml                                          | True        | qc-metrics, deliverable                   | audit, cg             |
| tumor-cram, cram                                               | True        | tumor, cram                               | deliver, scout        |
| tumor-cram-index, cram                                         | True        | tumor, cram-index                         | deliver, scout        |
| normal-cram, cram                                              | False       | normal, cram                              | deliver, scout        |
| cram, normal-cram-index                                        | False       | normal, cram-index                        | deliver, scout        |
| snv, vcf-tumor, dnascope, germline-vcf-tumor                   | True        | germline, vcf-snv-germline-tumor          | deliver               |
| snv, germline-vcf-tumor-index, vcf-tumor, dnascope             | True        | germline, vcf-snv-germline-tumor-index    | deliver               |
| snv, vcf-normal, germline-vcf-normal, dnascope                 | False       | germline, vcf-snv-germline-normal         | deliver               |
| snv, vcf-normal, germline-vcf-normal-index, dnascope           | False       | germline, vcf-snv-germline-normal-index   | deliver               |
| genotype-vcf-dnascope, vcf-dnascope                            | False       | dnascope, normal, vcf                     | cg, genotype          |
| genotype-vcf-dnascope-index, vcf-dnascope                      | False       | dnascope, normal, vcf-index               | cg, genotype          |
| manta-germline, sv, vcf-tumor, germline-vcf-tumor              | True        | germline, vcf-sv-germline-tumor           | deliver               |
| manta-germline, sv, vcf-tumor, germline-vcf-tumor-index        | True        | germline, vcf-sv-germline-tumor-index     | deliver               |
| manta-germline, vcf-normal, sv, germline-vcf-normal            | False       | germline, vcf-sv-germline-normal          | deliver               |
| manta-germline, vcf-normal, sv, germline-vcf-normal-index      | False       | germline, vcf-sv-germline-normal-index    | deliver               |
| vcf-svdb, research-vcf-svdb                                    | True        | svdb, vcf-sv                              | deliver               |
| vcf-svdb, research-vcf-svdb-index                              | True        | svdb, vcf-sv-index                        | deliver               |
| research-vcf-pass-svdb, vcf-pass-svdb                          | True        | svdb, vcf-sv-research                     | deliver               |
| research-vcf-pass-svdb-index, vcf-pass-svdb                    | True        | svdb, vcf-sv-research-index               | deliver               |
| vcf-pass-svdb, clinical-vcf-pass-svdb                          | True        | svdb, vcf-sv-clinical                     | deliver, scout        |
| vcf-pass-svdb, clinical-vcf-pass-svdb-index                    | True        | svdb, vcf-sv-clinical-index               | deliver, scout        |
| research-vcf-tnscope, vcf-tnscope                              | False       | tnscope, vcf-snv                          | deliver               |
| research-vcf-tnscope-index, vcf-tnscope                        | False       | tnscope, vcf-snv-index                    | deliver               |
| vcf-pass-tnscope, research-vcf-pass-tnscope, snv               | False       | tnscope, vcf-snv-research                 | deliver               |
| research-vcf-pass-tnscope-index, vcf-pass-tnscope, snv         | False       | tnscope, vcf-snv-research-index           | deliver               |

**Review by diitaz93 — APPROVED** [review]
Looks great 👍

**Comment by henrikstranneheim** [comment]
### Deployed to prod
```
:28] [hiseq.clinical@hasta:~] [P_base]  $ conda create --name P_hermes python=3,12.5 pip
Retrieving notices: ...working... done
Channels:
 - bioconda
 - defaults
 - conda-forge
 - nodefaults
Platform: linux-64
Collecting package metadata (repodata.json): / failed

CondaError: KeyboardInterrupt

[08:30] [hiseq.clinical@hasta:~] [P_base]  $ conda create --name P_hermes python=3.12.5 pip
Channels:
 - bioconda
 - defaults
 - conda-forge
 - nodefaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/proj/production/bin/miniconda3/envs/P_hermes

  added / updated specs:
    - pip
    - python=3.12.5


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ld_impl_linux-64-2.40      |       h12ee557_0         710 KB
    ------------------------------------------------------------
                                           Total:         710 KB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h5eee18b_6
  ca-certificates    pkgs/main/linux-64::ca-certificates-2024.7.2-h06a4308_0
  expat              pkgs/main/linux-64::expat-2.6.3-h6a678d5_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.40-h12ee557_0
  libffi             pkgs/main/linux-64::libffi-3.4.4-h6a678d5_1
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1
  libuuid            pkgs/main/linux-64::libuuid-1.41.5-h5eee18b_0
  ncurses            pkgs/main/linux-64::ncurses-6.4-h6a678d5_0
  openssl            pkgs/main/linux-64::openssl-3.0.15-h5eee18b_0
  pip                pkgs/main/linux-64::pip-24.2-py312h06a4308_0
  python             pkgs/main/linux-64::python-3.12.5-h5148396_1
  readline           pkgs/main/linux-64::readline-8.2-h5eee18b_0
  setuptools         pkgs/main/linux-64::setuptools-75.1.0-py312h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.45.3-h5eee18b_0
  tk                 pkgs/main/linux-64::tk-8.6.14-h39e8969_0
  tzdata             pkgs/main/noarch::tzdata-2024a-h04d1e81_0
  wheel              pkgs/main/linux-64::wheel-0.44.0-py312h06a4308_0
  xz                 pkgs/main/linux-64::xz-5.4.6-h5eee18b_1
  zlib               pkgs/main/linux-64::zlib-1.2.13-h5eee18b_1


Proceed ([y]/n)? y¨
Invalid choice: y¨
Proceed ([y]/n)? y


Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate P_hermes
#
# To deactivate an active environment, use
#
#     $ conda deactivate

k.stranneheim@hasta:~] [P_base] $ bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-prod.sh -e P_hermes -t hermes -b main
/home/henrik.stranneheim/tmp/tmplpswfroi: line 3: /home/proj/production/bin/miniconda3/envs/P_hermes/bin/hermes: No such file or directory

ERROR conda.cli.main_run:execute(124): `conda run /home/proj/production/bin/miniconda3/envs/P_hermes/bin/hermes --version` failed. (See above for error)
Collecting git+https://github.com/Clinical-Genomics/hermes@main
  Cloning https://github.com/Clinical-Genomics/hermes (to revision main) to ./tmp/pip-req-build-hq8lsxul
  Running command git clone --quiet https://github.com/Clinical-Genomics/hermes /home/henrik.stranneheim/tmp/pip-req-build-hq8lsxul
  Resolved https://github.com/Clinical-Genomics/hermes to commit ea850e545a01bd0467fc758834573fd313ec77ff
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cg-hermes
  Building wheel for cg-hermes (pyproject.toml) ... done
  Created wheel for cg-hermes: filename=cg_hermes-5.0.0-py3-none-any.whl size=34591 sha256=c228bd37032f55b8584b0e6edeb4a5bb6d5171eb68dacbd6ff677157a410139e
  Stored in directory: /home/henrik.stranneheim/tmp/pip-ephem-wheel-cache-eysxptt6/wheels/74/79/ce/db2a7ab6f19728a2e1aed64c7dc39ffd5a0369f25efa5aa3d9
Successfully built cg-hermes
Installing collected packages: cg-hermes
Successfully installed cg-hermes-5.0.0
Collecting git+https://github.com/Clinical-Genomics/hermes@main
  Cloning https://github.com/Clinical-Genomics/hermes (to revision main) to ./tmp/pip-req-build-hxr00ztz
  Running command git clone --quiet https://github.com/Clinical-Genomics/hermes /home/henrik.stranneheim/tmp/pip-req-build-hxr00ztz
  Resolved https://github.com/Clinical-Genomics/hermes to commit ea850e545a01bd0467fc758834573fd313ec77ff
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting bump2version (from cg-hermes==5.0.0)
  Using cached bump2version-1.0.1-py2.py3-none-any.whl.metadata (17 kB)
Collecting coloredlogs (from cg-hermes==5.0.0)
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Collecting pydantic (from cg-hermes==5.0.0)
  Using cached pydantic-2.9.2-py3-none-any.whl.metadata (149 kB)
Collecting pyyaml (from cg-hermes==5.0.0)
  Using cached PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting tabulate (from cg-hermes==5.0.0)
  Using cached tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Collecting typer (from cg-hermes==5.0.0)
  Using cached typer-0.12.5-py3-none-any.whl.metadata (15 kB)
Collecting typing-extensions (from cg-hermes==5.0.0)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting humanfriendly>=9.1 (from coloredlogs->cg-hermes==5.0.0)
  Using cached humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Collecting annotated-types>=0.6.0 (from pydantic->cg-hermes==5.0.0)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.23.4 (from pydantic->cg-hermes==5.0.0)
  Using cached pydantic_core-2.23.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting click>=8.0.0 (from typer->cg-hermes==5.0.0)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting shellingham>=1.3.0 (from typer->cg-hermes==5.0.0)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=10.11.0 (from typer->cg-hermes==5.0.0)
  Using cached rich-13.8.1-py3-none-any.whl.metadata (18 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=10.11.0->typer->cg-hermes==5.0.0)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=10.11.0->typer->cg-hermes==5.0.0)
  Using cached pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->cg-hermes==5.0.0)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached bump2version-1.0.1-py2.py3-none-any.whl (22 kB)
Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Using cached pydantic-2.9.2-py3-none-any.whl (434 kB)
Using cached pydantic_core-2.23.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Using cached PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (767 kB)
Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
Using cached typer-0.12.5-py3-none-any.whl (47 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Using cached rich-13.8.1-py3-none-any.whl (241 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: typing-extensions, tabulate, shellingham, pyyaml, pygments, mdurl, humanfriendly, click, bump2version, annotated-types, pydantic-core, markdown-it-py, coloredlogs, rich, pydantic, typer
Successfully installed annotated-types-0.7.0 bump2version-1.0.1 click-8.1.7 coloredlogs-15.0.1 humanfriendly-10.0 markdown-it-py-3.0.0 mdurl-0.1.2 pydantic-2.9.2 pydantic-core-2.23.4 pygments-2.18.0 pyyaml-6.0.2 rich-13.8.1 shellingham-1.5.4 tabulate-0.9.0 typer-0.12.5 typing-extensions-4.12.2
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/henrik.stranneheim
done.
Log deploy... done.
hermes version: 5.0.0
[henrik.stranneheim@hasta:~] [P_base] $ hermes export tags balsamic
Usage: hermes export tags [OPTIONS]
Try 'hermes export tags --help' for help.
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Got unexpected extra argument (balsamic)                                                                                                                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[henrik.stranneheim@hasta:~] [P_base] $ hermes export tags --workflow balsamic
2024-09-30 08:38:26 hasta.scilifelab.se cg_hermes.cli.export[259371] INFO Running export tags for workflow: balsamic
| Balsamic tags                                                  | Mandatory   | HK tags                                   | Used by               |
|----------------------------------------------------------------|-------------|-------------------------------------------|-----------------------|
| balsamic-config                                                | True        | balsamic-config                           | audit, cg             |
| balsamic-report                                                | True        | balsamic-report                           | audit                 |

**Pull request merged**
